### ISSUE TITLE
useless error message in zed request errors

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#224]
This is a

* [x] bug
* [ ] enhancement

spryker/zed-request 3.4.2

### What you did
When an error in a zed request occurs, instead of the zed error message you get the following:
```Noticed exception 'Spryker\Shared\ZedRequest\Client\Exception\RequestException' with message 'Incorrect HOST_ZED config, expected `www.MYSERVER.com`, got `zed.MYSERVER.com`. Set the URLs in your Shared/config_default_DE.php or env specific config files.```
You tried to enhance some error messages in the following commit but now it doesn't makes any sense at all. The Zed Host will never be the same as the Yves Host. An what is with the actual error message?
https://github.com/spryker/zed-request/commit/9883c5f6fdb4b271586eb956b575809633f580f8

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Should be fixed in https://github.com/spryker/zed-request/releases/tag/3.4.4.

**Comment by AndromedaXP** [comment]
@tvaleriy Yes u did, but therefore the next bug came in, because of 
```return Config::get(ApplicationConstants::PORT_ZED) ?: static::DEFAULT_PORT```

When u don't have ApplicationConstants::PORT_ZED set, this throws an exception. Maybe better
```return Config::get(ApplicationConstants::PORT_ZED, static::DEFAULT_PORT)```
???
The same with the ssl port in AbstractHttpClient:178

**Comment by tvaleriy** [comment]
Thank you for the feedback. New ticket is created. I will notify when it is fixed.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP, this should be fixed in https://github.com/spryker/zed-request/releases/tag/3.5.2.

**Comment by kfrohwein** [comment]
Honestly the message is still not very helpful. I have a

`cURL error 28: Resolving timed out after 1537 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

and the message you give me is
```
Failed to complete request with server authority http://zed.so.akona.local.
Configured with (SSL Disabled) zed.so.akona.local: in /data/shop/development/current/config/Shared/config_default.php. Error: Stacktrace:
```

I would suggest to just add the original message to your own. Or I have to use xdebug like I just did.

Cheers, Karsten :)

**Comment by tvaleriy** [comment]
Hi Karsten,
thank you for the feedback!
I'll escalate this topic to our development team once again.

Best,
Spryker Support Team
